{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.minio.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.minio.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.minio.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.minio.name }}
    spec:
      nodeSelector:
{{ toYaml .Values.minio.nodeSelector | indent 8 }}
      containers:
        - name: {{ .Values.minio.name }}
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          args:
            - server
            - /data
            - --console-address
            - ":{{ .Values.minio.consoleService.port }}"
          ports:
            - name: api
              containerPort: {{ .Values.minio.apiService.port }}
            - name: console
              containerPort: {{ .Values.minio.consoleService.port }}
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: MINIO_ROOT_PASSWORD
          volumeMounts:
            - name: minio-storage
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: {{ .Values.minio.apiService.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: {{ .Values.minio.apiService.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.minio.resources | indent 12 }}
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: {{ .Values.minio.storage.pvcName }}
{{- end }}