---
- name: Add Bitnami Helm repository
  ansible.builtin.command: >
    helm repo add {{ bitnami_helm_repo_name }} {{ bitnami_helm_repo_url }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: bitnami_repo_add
  changed_when: "'has been added' in bitnami_repo_add.stdout"
  failed_when:
    - bitnami_repo_add.rc != 0
    - "'already exists' not in bitnami_repo_add.stderr"

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false

- name: Create demo namespace
  ansible.builtin.command: kubectl create namespace {{ demo_app_namespace }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: demo_namespace_create
  changed_when: "'created' in demo_namespace_create.stdout"
  failed_when:
    - demo_namespace_create.rc != 0
    - "'AlreadyExists' not in demo_namespace_create.stderr"

- name: Get current demo-nginx Helm release values
  ansible.builtin.command: >
    helm get values {{ demo_app_release_name }} -n {{ demo_app_namespace }} --all -o yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: demo_nginx_current_values
  changed_when: false
  failed_when: false

- name: Deploy or upgrade nginx with Helm
  ansible.builtin.command: >
    helm upgrade --install {{ demo_app_release_name }} {{ demo_app_chart }}
    --namespace {{ demo_app_namespace }}
    --set service.type={{ demo_app_service_type }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: demo_nginx_helm_upgrade
  changed_when: >
    demo_nginx_current_values.rc != 0 or
    ('type: ' ~ demo_app_service_type) not in demo_nginx_current_values.stdout

- name: Show demo pods
  ansible.builtin.command: kubectl get pods -n {{ demo_app_namespace }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: demo_pods
  changed_when: false

- name: Show demo service
  ansible.builtin.command: kubectl get svc -n {{ demo_app_namespace }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: demo_service
  changed_when: false

- name: Print demo status
  ansible.builtin.debug:
    msg:
      - "{{ demo_pods.stdout_lines }}"
      - "{{ demo_service.stdout_lines }}"