{{- if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.minio.storage.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.minio.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storage.size }}
{{- end }}