[k8s_control_plane]
k8s-master-01 ansible_host=192.168.1.15 ansible_user=devops ansible_python_interpreter=/usr/bin/python3

[k8s_workers]
k8s-worker-01 ansible_host=192.168.1.16 ansible_user=devops ansible_python_interpreter=/usr/bin/python3

[k8s_cluster:children]
k8s_control_plane
k8s_workers
