apiVersion: v1
kind: Service
metadata:
  name: data-api
  namespace: data-platform
spec:
  type: ClusterIP
  selector:
    app: data-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000