apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-processing
  namespace: data-platform
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: data-processing
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: ghcr-secret
          containers:
            - name: data-processing
              image: ghcr.io/elmed05/data-processing-job:0.1.0
              imagePullPolicy: IfNotPresent
              env:
                - name: DB_HOST
                  value: postgres
                - name: DB_PORT
                  value: "5432"
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_DB
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
                - name: MINIO_ENDPOINT
                  value: minio-api:9000
                - name: MINIO_PROCESSED_BUCKET
                  value: processed
                - name: MINIO_SECURE
                  value: "false"
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: MINIO_ROOT_USER
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: MINIO_ROOT_PASSWORD
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi