apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-generator
  namespace: data-platform
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: data-generator
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: ghcr-secret
          containers:
            - name: data-generator
              image: ghcr.io/elmed05/data-generator:0.1.0
              imagePullPolicy: IfNotPresent
              env:
                - name: API_BASE_URL
                  value: "http://data-api:8000"
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 250m
                  memory: 256Mi