---
- name: Generate Kubernetes join command on control plane
  hosts: k8s_control_plane
  become: true
  gather_facts: false

  tasks:
    - name: Generate kubeadm join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: kubeadm_join_command
      changed_when: false

    - name: Store join command as fact
      ansible.builtin.set_fact:
        worker_join_command: "{{ kubeadm_join_command.stdout }} --cri-socket=unix:///run/containerd/containerd.sock"

    - name: Show generated join command
      ansible.builtin.debug:
        msg: "{{ worker_join_command }}"


- name: Join worker nodes to Kubernetes cluster
  hosts: k8s_workers
  become: true
  gather_facts: false

  tasks:
    - name: Check if worker already joined the cluster
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join worker node to cluster
      ansible.builtin.shell: "{{ hostvars[groups['k8s_control_plane'][0]].worker_join_command }}"
      when: not kubelet_conf.stat.exists
      register: join_result
      changed_when: true

    - name: Show join result
      ansible.builtin.debug:
        var: join_result.stdout_lines
      when: join_result is defined and join_result.stdout_lines is defined

    - name: Worker already joined
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is already part of the Kubernetes cluster."
      when: kubelet_conf.stat.exists